### ISSUE TITLE
Failed to install packages

### ISSUE THREAD

**Issue by manh21** [FahrulID/virtual-gamepad#1]
![image](https://user-images.githubusercontent.com/31276236/149658685-6e7b4e40-6fbc-425f-9087-434509c53e8e.png)

**Comment by FahrulRPutra** [comment]
Can you provide the full error ???
Did you have Python installed ???

I'm using node version v16.13.1

**Comment by manh21** [comment]
Full error code
```bash
npm ERR! code 1
npm ERR! path C:\laragon\repo\virtual-gamepad\src\node_modules\vigemclient
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.2.0
npm ERR! gyp info using node@16.11.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.6.1 found at "C:\laragon\bin\python\python-3.6.1\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\laragon\bin\nodejs\node-v16.11.1-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\laragon\bin\nodejs\node-v16.11.1-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\laragon\bin\nodejs\node-v16.11.1-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\laragon\bin\nodejs\node-v16.11.1-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\laragon\bin\nodejs\node-v16.11.1-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\laragon\bin\nodejs\node-v16.11.1-win-x64\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7  
npm ERR! gyp ERR! stack     at C:\laragon\bin\nodejs\node-v16.11.1-win-x64\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\laragon\\bin\\nodejs\\node-v16.11.1-win-x64\\node.exe" "C:\\laragon\\bin\\nodejs\\node-v16.11.1-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\laragon\repo\virtual-gamepad\src\node_modules\vigemclient
npm ERR! gyp ERR! node -v v16.11.1
npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Acer\AppData\Local\npm-cache\_logs\2022-01-16T11_47_37_722Z-debug.log
```
Python version:
![image](https://user-images.githubusercontent.com/31276236/149663077-581a93fd-66c8-4081-86eb-b94beb76cf87.png)

Node Version:
![image](https://user-images.githubusercontent.com/31276236/149663107-daa56be8-7f92-44aa-86bc-7aa7b5faa22c.png)

**Comment by FahrulRPutra** [comment]
Can you try this solution, as stated in the error log ???

![image](https://user-images.githubusercontent.com/49786305/149663245-7964d264-c6f5-4636-a544-71a7f6ea3782.png)

**Comment by manh21** [comment]
Why this program need Visual Studio tho?

**Comment by FahrulRPutra** [comment]
> Why this program need Visual Studio tho?

Because there is a node addon inside the package.

**Comment by FahrulRPutra** [comment]
But if you don't want to install VS 2017++, you can try the released build on the release page.

**Comment by manh21** [comment]
Probably should update the docs a specially the prerequisite

**Comment by FahrulRPutra** [comment]
> Probably should update the docs a specially the prerequisite

Thank u for the suggestion, as I forget to mention it inside the prerequisite.
